apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-test
resources:
  - namespace.yaml
  - podinfo-src.yaml
  - release.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=values-custom.yaml
configurations:
  - kustomizeconfig.yaml
