apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - release.yaml
  - ../charts/podinfo/templates/deployment.yaml
  - ../charts/podinfo/templates/hpa.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=values-custom.yaml
configurations:
  - kustomizeconfig.yaml
