apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=values-custom.yaml
configurations:
  - kustomizeconfig.yaml
