apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo-test
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/jingda/podinfo
  # ignore: |
  #   # exclude all
  #   /*
  #   # include charts directory
  #   !/charts/
