apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-test
  namespace: podinfo-test
spec:
  interval: 5m
  releaseName: podinfo-test
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
        # namespace: podinfo-test
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
  targetNamespace: podinfo-test
  