apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 30s
  releaseName: podinfo
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: podinfo
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
  targetNamespace: podinfo
  